import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Layout = ({children, title}) => {
    return (
      <div>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className="h-14 p-2 flex items-center justify-center  shadow-[0_4px_50px_#0284c7] mb-10">
          <Link href="/" legacyBehavior>
            <a>
              <img src="/logo.webp" alt="logo" height={36} width={124} />
            </a>
          </Link>
        </header>

        <main className="container mx-auto">{children}</main>
      </div>
    );
};

export default Layout;
